name: Log in to Gov UK PaaS
description: Log in to Gov UK PaaS
inputs: 
  spacename:
    description: "Name of space"
    required: true
  username:
    description: "Username for deploying to Gov UK PaaS"
    required: true
  password:
    description: "Password for deploying to Gov UK PaaS"
    required: true
  organisation:
    description: "The organisation within Gov UK PaaS"
    required: true
runs: 
  using: "composite"
  steps: 
    - name: Log in to Gov PaaS
      shell: bash
      run: cf login -a api.london.cloud.service.gov.uk -u ${{ inputs.username }} -p ${{ inputs.password }} # See https://docs.cloud.service.gov.uk/using_ci.html#configure-your-ci-tool-accounts
    - name: Set Gov PaaS org and space
      shell: bash
      run: cf target -o ${{ inputs.organisation }} -s ${{ inputs.spacename }}