name: Configure autoscaling
description: Configure the autoscaling policy for an application
inputs:
  application-name:
    description: "The name of the application to deploy to Gov UK PaaS"
    required: true
  autoscaling-policy:
    description: "The filename for the autoscaling policy see: https://docs.cloud.service.gov.uk/managing_apps.html#example"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Install autoscaling plugin
      shell: bash
      run: cf install-plugin -r CF-Community app-autoscaler-plugin -f
    - name: Attach autoscaling policy to app
      shell: bash
      run: cf attach-autoscaling-policy ${{ inputs.application-name }} ${{ inputs.autoscaling-policy }}