name: Automated checks
on:
  pull_request:
    branches:
      - main

env:
  application-name: hrsds_prototype

jobs:
  format:
    name: "Check code formatting"
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          activate-environment: ${{ env.application-name }}
          environment-file: environment.yml
      - name: Run formatter
        run: black --check ./

  lint:
    name: "Check code for linting errors"
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          activate-environment: ${{ env.application-name }}
          environment-file: environment.yml
      - name: Run linter
        run: pylint $(pwd)

  test:
    name: "Run tests"
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          activate-environment: ${{ env.application-name }}
          environment-file: environment.yml
      - name: Execute tests
        run: python -u -m pytest --headless tests 
